#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: harbor.dev.livefire.lab/<project_name>/k8s:k8s-simple
  #@ if not data.values.push_images_repo or len(data.values.push_images_repo) == 0:
  #@   assert.fail("Expected push_images_repo to be non-empty. Example: harbor.dev.livefire.lab/<project_name>/k8s:k8s-simple)
  #@ end
  newImage: #@ data.values.push_images_repo
