---
apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: simple-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
#  namespace: default
  name: simple-app
spec:
#  replicas: 2
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-app
        image: harbor.dev.livefire.lab/<project_name>/k8s:k8s-sample
        env:
        - name: HELLO_MSG
          value: stranger
