---
apiVersion: v1
kind: Service
metadata:
#  namespace: default
  name: simple-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
#  namespace: default
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-app
        image: harbor.dev.livefire.lab/library/tbs/tiny@sha256:6de8182fb9ba01d15b067d6a50a25f00fa9e8e6059daf881a5df9ad673b46910
        env:
        - name: HELLO_MSG
          value: stranger
